name: CI

on:
  push:

jobs:
  build-and-run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install dotnet-combine
      run: dotnet tool install -g dotnet-combine

    - name: Build combined Program.cs
      working-directory: ./TopLevelChallenge
      run: dotnet combine single-file . --output ../TopLevelChallenge.Generated/Program.g.cs --overwrite --format

    - name: Run code from both top level statements
      working-directory: ./TopLevelChallenge.Generated
      run: dotnet run -c Release
